version: '3'
services:
  bitcoin-jvm:
    image: quarkus/bitcoin-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-bitcoin:3306/api?autoReconnect=true
    networks:
      - mysql-db
    ports:
      - 8080:8080
    depends_on:
      - mysql-bitcoin
  mysql-bitcoin:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Caronte1212#"
      MYSQL_DATABASE: "bitcoin"
    ports:
      - "3306:3306"
    volumes:
      - mysql.bitcoin:/var/lib/mysql
    networks:
      - mysql-db

networks:
  mysql-db:
    driver: bridge

volumes:
  mysql.bitcoin: